# Generated by Django 5.2.9 on 2026-01-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
